# Generated by Django 4.1.3 on 2023-04-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ('subdivision_name',), 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='subdivision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='docs_data.subdivision'),
            preserve_default=False,
        ),
    ]
