# Generated by Django 4.1.3 on 2023-04-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs_data.subdivision'),
        ),
    ]
