# Generated by Django 4.1.3 on 2023-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_data', '0002_alter_customuser_subdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
    ]
