# Generated by Django 4.1.3 on 2023-04-11 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_data', '0003_region_date_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='docdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (кто добавил документ)'),
            preserve_default=False,
        ),
    ]
