# Generated by Django 4.1.3 on 2023-04-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_data', '0003_categoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='docs', verbose_name='Файл')),
                ('file_name', models.TextField(verbose_name='Название документа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание документа')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_data.categoryitem', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('-id',),
            },
        ),
    ]
