# Generated by Django 4.1.3 on 2023-04-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_data', '0004_docdata_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ('-id',), 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='docdata',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs_data.region', verbose_name='Район'),
        ),
    ]
