# Generated by Django 4.1.3 on 2023-04-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_data', '0004_docdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='docdata',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
    ]
