# Generated by Django 4.1.3 on 2023-04-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_data', '0005_docdata_doc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
    ]
