# Generated by Django 4.1.3 on 2023-04-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_data', '0005_alter_subdivision_options_docdata_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdata',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs_data.categoryitem', verbose_name='Категория'),
        ),
    ]
